{{- range .Values.bebot.instances }}
{{- if eq .createSecret false }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-conf-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ default "1h" .secretRefreshInterval }}
  secretStoreRef:
    name: {{ default "gcp-clusterstore" .secretStoreName }}
    kind: {{ default "ClusterSecretStore" .secretStoreKind }}
  target:
    name: {{ $.Release.Name }}-conf-{{ .name }}
    creationPolicy: Owner
    template:
      data:
        Bot.conf: |
          <?php
            $ao_username = "{{ .ao_username }}";
            $ao_password = "{{"{{"}} .ao_password {{"}}"}}";
            $bot_name = "{{ .bot_name }}";
            $dimension = "{{ .dimension }}";
            $guild = "{{ .guild | default "" }}";
            $owner = "{{ .botOwner }}";
          {{ range .superAdmins -}}
            $super_admin["{{ . }}"] = true;
          {{ end -}}
            $slave = "{{ .slave | default "" }}";
            $periph = {{ .periph | default 0 }};
          {{ range .otherBots -}}
            $other_bots["{{ . }}"] = true;
          {{ end -}}
            $guildbot = {{ if .raidbot }}false{{ else }}true{{ end }};
            $guild_id = {{ .guildId }};
            $log = "{{ .log | default "chat" }}";
            $log_path = "{{ .logPath | default "./log" }}";
            $log_timestamp = "{{ .logTimestamp | default "none" }}";
            $core_directories = "{{ .coreDirectories | default "" }}";
            $module_directories = "{{ .moduleDirectories | default "" }}";
            $command_prefix = "{{ .commandPrefix | default "!" }}";
            $cron_delay = {{ .cronDelay | default 30 }};
            $tell_delay = {{ .tellDelay | default 2222 }};
            $reconnect_time = {{ .reconnectTime | default 60 }};
            if(is_numeric($dimension))
              $max_blobsize = 12000;
            else
              $max_blobsize = 8000;
            $accessallbots = {{ if .accessAllBots }}TRUE{{ else }}FALSE{{ end }};
            $use_proxy_server = {{ if .useProxyServer }}true{{ else }}false{{ end }};
            $proxy_server_address = "{{ .proxyServerAddress | default "" }}";
          ?>
        Mysql.conf: |
          <?php
            $dbase = "{{"{{"}} .mariadb_database {{"}}"}}";
            $user = "{{"{{"}} .mariadb_user {{"}}"}}";
            $pass = "{{"{{"}} .mariadb_password {{"}}"}}";
            $server = "{{"{{"}} .mariadb_host {{"}}"}}";
          ?>
        mariadb_user: "{{"{{"}} .mariadb_user {{"}}"}}"
        mariadb_password: "{{"{{"}} .mariadb_password {{"}}"}}"
        mariadb_database: "{{"{{"}} .mariadb_database {{"}}"}}"
        Aoaccounts.conf: ""
        ServerList.php: |
{{ $.Files.Get "files/ServerList.php" | indent 10 }}
  data:
    - secretKey: ao_password
      remoteRef:
        key: {{ .gcpSecretName }}
        property: ao_password
        decodingStrategy: None
    - secretKey: mariadb_user
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_user
        decodingStrategy: None
    - secretKey: mariadb_password
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_password
        decodingStrategy: None
    - secretKey: mariadb_database
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_database
        decodingStrategy: None
    - secretKey: mariadb_host
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_host
        decodingStrategy: None
---
{{- end }}
{{- end }}
