{{- range .Values.bebot.instances }}
{{- if eq .createSecret false }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-conf-{{ .name }}
spec:
  refreshInterval: {{ default "1h" .secretRefreshInterval }}
  secretStoreRef:
    name: {{ default "gcp-clusterstore" .secretStoreName }}
    kind: {{ default "ClusterSecretStore" .secretStoreKind }}
  target:
    name: {{ $.Release.Name }}-conf-{{ .name }}
    creationPolicy: Owner
    template:
      data:
        Bot.conf: |
          <?php
            $ao_username = "{{ .ao_username }}";
            $ao_password = "{{"{{"}} .ao_password {{"}}"}}";
            $bot_name = "{{ .bot_name }}";
            $dimension = "{{ .dimension }}";
            $guild = "";
            $owner = "{{ .botOwner }}";
          {{ range .superAdmins -}}
            $super_admin["{{ . }}"] = true;
          {{ end -}}
            $slave = "";
            $periph = "0";
            $guildbot = {{ if .raidbot }}false{{ else }}true{{ end }};
            $guild_id = {{ .guildId }};
            $log = "chat";
            $log_path = "./log";
            $log_timestamp = "none";
            if(is_numeric($dimension))
              $max_blobsize = 12000;
            else
              $max_blobsize = 8000;
            $accessallbots = FALSE;
            $command_prefix = "!";
            $cron_delay = 30;
            $tell_delay = 2222;
            $reconnect_time = 60;
            $use_proxy_server = false;
            $proxy_server_address = "";
          ?>
        Mysql.conf: |
          <?php
            $dbase = "{{"{{"}} .mariadb_database {{"}}"}}";
            $user = "{{"{{"}} .mariadb_user {{"}}"}}";
            $pass = "{{"{{"}} .mariadb_password {{"}}"}}";
            $server = "{{"{{"}} .mariadb_host {{"}}"}}";
          ?>
        mariadb_user: "{{"{{"}} .mariadb_user {{"}}"}}"
        mariadb_password: "{{"{{"}} .mariadb_password {{"}}"}}"
        mariadb_database: "{{"{{"}} .mariadb_database {{"}}"}}"
        Aoaccounts.conf: ""
        ServerList.php: |
{{ $.Files.Get "files/ServerList.php" | indent 10 }}
  data:
    - secretKey: ao_password
      remoteRef:
        key: {{ .gcpSecretName }}
        property: ao_password
    - secretKey: mariadb_user
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_user
    - secretKey: mariadb_password
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_password
    - secretKey: mariadb_database
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_database
    - secretKey: mariadb_host
      remoteRef:
        key: {{ .gcpSecretName }}
        property: mariadb_host
---
{{- end }}
{{- end }}
