{{- range .Values.bebot.instances }}
{{- if ne .createSecret false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-conf-{{ .name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  Mysql.conf: |-
{{ tpl ( $.Files.Get "files/Mysql.conf.dist" ) (dict "raidbot" .raidbot "mariadbUser" (.mariadbUser | default "" | b64dec) "mariadbPassword" (.mariadbPassword | default "" | b64dec) "mariadbDatabase" (.mariadbDatabase | default "" | b64dec) "mariadbHost" (default (printf "%s-mariadb" $.Release.Name | b64enc) .mariadbHost | b64dec) ) | indent 4 }}
  Bot.conf: |-
{{ tpl ( $.Files.Get "files/Bot.conf.dist" ) (dict "ao_username" .ao_username "ao_password" (.ao_password | default "" | b64dec) "bot_name" .bot_name "dimension" .dimension "guildId" .guildId "botOwner" .botOwner "superAdmins" .superAdmins ) | indent 4 }}
  mariadb_user: {{ .mariadbUser | default "" | b64dec | quote }}
  mariadb_password: {{ .mariadbPassword | default "" | b64dec | quote }}
  mariadb_database: {{ .mariadbDatabase | default "" | b64dec | quote }}
  Aoaccounts.conf: |-
{{ $.Files.Get "files/Aoaccounts.conf.dist" | indent 4 }}
  ServerList.php: |-
{{ $.Files.Get "files/ServerList.php" | indent 4 }}
---
{{- end }}
{{- end }}