{{- range .Values.bebot.instances }}
{{- if ne .createSecret false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-conf-{{ .name }}
type: Opaque
stringData:
  Mysql.conf: |-
{{ tpl ( $.Files.Get "files/Mysql.conf.dist" ) (dict "raidbot" .raidbot "mariadbUser" .mariadbUser "mariadbPassword" .mariadbPassword "mariadbDatabase" .mariadbDatabase "mariadbHost" (default "bebot-mariadb" .mariadbHost) ) | indent 4 }}
  Bot.conf: |-
{{ tpl ( $.Files.Get "files/Bot.conf.dist" ) (dict "ao_username" .ao_username "ao_password" .ao_password "bot_name" .bot_name "dimension" .dimension "guildId" .guildId "botOwner" .botOwner "superAdmins" .superAdmins ) | indent 4 }}
  Aoaccounts.conf: |-
{{ $.Files.Get "files/Aoaccounts.conf.dist" | indent 4 }}
  ServerList.php: |-
{{ $.Files.Get "files/ServerList.php" | indent 4 }}
---
{{- end }}
{{- end }}