{{- if and .Values.bebot.mariadb.enabled (eq .Values.bebot.mariadb.createSecret false) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mariadb-root
spec:
  refreshInterval: {{ default "1h" .Values.bebot.mariadb.secretRefreshInterval }}
  secretStoreRef:
    name: {{ default "gcp-clusterstore" .Values.bebot.mariadb.secretStoreName }}
    kind: {{ default "ClusterSecretStore" .Values.bebot.mariadb.secretStoreKind }}
  target:
    name: {{ .Release.Name }}-mariadb-root
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: {{ .Values.bebot.mariadb.gcpSecretName }}
        property: root-password
    - secretKey: root-user
      remoteRef:
        key: {{ .Values.bebot.mariadb.gcpSecretName }}
        property: root-user
{{- end }}
