{{- if and .Values.bebot.mariadb.enabled .Values.bebot.mariadb.backup.enabled }}
{{- if and (eq (.Values.bebot.mariadb.backup.destination | default "pvc") "s3") .Values.bebot.mariadb.backup.s3.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mariadb-backup-s3-creds
spec:
  refreshInterval: {{ .Values.bebot.mariadb.backup.s3.externalSecret.secretRefreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.bebot.mariadb.backup.s3.externalSecret.secretStoreName | default "gcp-clusterstore" }}
    kind: {{ .Values.bebot.mariadb.backup.s3.externalSecret.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.bebot.mariadb.backup.s3.credentialsSecret }}
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: {{ .Values.bebot.mariadb.backup.s3.externalSecret.gcpSecretName }}
        property: access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: {{ .Values.bebot.mariadb.backup.s3.externalSecret.gcpSecretName }}
        property: secret-access-key
{{- end }}
{{- end }}
