{{- range $i, $instance := .Values.bebot.instances }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-serviceaccount-{{ $instance.name }}
{{- with $.Values.bebot.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}