{{- range .Values.bebot.instances }}
{{- if ne .createSecret false }}
{{- $conf := deepCopy . }}
{{- $_ := set $conf "mariadbHost" (default (printf "%s-mariadb" $.Release.Name) .mariadbHost) }}
{{- $_ := set $conf "ao_password" (.ao_password | default "") }}
{{- $_ := set $conf "mariadbUser" (.mariadbUser | default "") }}
{{- $_ := set $conf "mariadbPassword" (.mariadbPassword | default "") }}
{{- $_ := set $conf "mariadbDatabase" (.mariadbDatabase | default "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-conf-{{ .name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  bot_conf.py: |-
{{ tpl ( $.Files.Get "files/bot_conf.py.dist" ) $conf | indent 4 }}
  mariadb_user: {{ .mariadbUser | default "" | quote }}
  mariadb_password: {{ .mariadbPassword | default "" | quote }}
  mariadb_database: {{ .mariadbDatabase | default "" | quote }}
---
{{- end }}
{{- end }}
