---
apiVersion: v2
name: bebot

description: Helm chart for bebot
type: application

appVersion: 2.23.1

version: 2.23.1

dependencies:
  - name: mariadb-operator-crds
    version: "26.6.0"
    repository: "https://mariadb-operator.github.io/mariadb-operator"
    condition: bebot.mariadbOperator.enabled
  - name: mariadb-operator
    version: "26.6.0"
    repository: "https://mariadb-operator.github.io/mariadb-operator"
    condition: bebot.mariadbOperator.enabled
