{{- if and .Values.bebot.mariadb.enabled .Values.bebot.mariadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mariadb-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - {{ .Values.bebot.mariadb.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.bebot.mariadb.persistence.storageClass }}
  storageClassName: {{ .Values.bebot.mariadb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.bebot.mariadb.persistence.size | default "1Gi" }}
{{- end }}
